import { formatCompactAmount } from "@/components/investigation/format";
import type { AaveActivityAggregates, AssetAggregate } from "@/lib/investigation/aggregates";

export function AggregateTable({ aggregates }: { aggregates: AaveActivityAggregates }) {
  const assets = Object.values(aggregates.perAsset);

  if (assets.length === 0) {
    return null;
  }

  return (
    <div>
      <p className="font-mono text-xs uppercase tracking-[0.14em] text-cyan">Section 05 — The exposure</p>
      <h2 className="font-display mt-3 text-4xl leading-tight text-foreground sm:text-5xl">Computed from the chain</h2>
      <p className="mt-3 max-w-lg font-mono text-xs uppercase tracking-[0.06em] text-muted">
        Deterministic totals from retrieved records — <span className="text-foreground/70">not generated by AI</span>
      </p>

      <div className="mt-8 overflow-x-auto border-y border-border">
        <table className="w-full min-w-[480px] border-collapse text-sm">
          <thead>
            <tr className="border-b border-border-strong text-left">
              <th className="px-4 pb-3 pt-3 text-xs font-normal uppercase tracking-[0.1em] text-muted-2">Asset</th>
              <th className="px-4 pb-3 pt-3 text-right text-xs font-normal uppercase tracking-[0.1em] text-muted-2">Supplied</th>
              <th className="px-4 pb-3 pt-3 text-right text-xs font-normal uppercase tracking-[0.1em] text-muted-2">Borrowed</th>
              <th className="px-4 pb-3 pt-3 text-right text-xs font-normal uppercase tracking-[0.1em] text-muted-2">Repaid</th>
              <th className="px-4 pb-3 pt-3 text-right text-xs font-normal uppercase tracking-[0.1em] text-muted-2">Net</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {assets.map((asset) => (
              <AggregateRow key={asset.symbol} asset={asset} />
            ))}
          </tbody>
        </table>
      </div>

      <p className="mt-3 font-mono text-xs text-muted-2">
        {aggregates.totalEventCount} total events ·{" "}
        {Object.entries(aggregates.eventCountByAction)
          .map(([action, count]) => `${action} ${count}`)
          .join(" · ")}
      </p>
    </div>
  );
}

function AggregateRow({ asset }: { asset: AssetAggregate }) {
  const supplied = formatCompactAmount(asset.totalSupply.normalized);
  const borrowed = formatCompactAmount(asset.totalBorrow.normalized);
  const repaid = formatCompactAmount(asset.totalRepay.normalized);
  const net = formatCompactAmount(asset.netBorrowExposure.normalized);
  const netNumeric = Number(asset.netBorrowExposure.normalized);

  const collateralSeized = asset.totalLiquidationCollateralSeized;
  const principalRepaidViaLiquidation = asset.totalLiquidationPrincipalRepaid;
  const hasLiquidation = collateralSeized.eventCount > 0 || principalRepaidViaLiquidation.eventCount > 0;

  return (
    <tr className="align-top">
      <td className="px-4 py-3 font-medium text-foreground">
        {asset.symbol}
        {hasLiquidation && (
          <p className="mt-0.5 max-w-[16rem] font-mono text-[11px] text-muted-2">
            {collateralSeized.eventCount > 0 &&
              `${formatCompactAmount(collateralSeized.normalized).display} seized as collateral`}
            {collateralSeized.eventCount > 0 && principalRepaidViaLiquidation.eventCount > 0 && " · "}
            {principalRepaidViaLiquidation.eventCount > 0 &&
              `${formatCompactAmount(principalRepaidViaLiquidation.normalized).display} repaid via liquidation`}
          </p>
        )}
      </td>
      <td className="px-4 py-3 text-right font-mono text-foreground/90" title={`${supplied.exact} ${asset.symbol} (exact)`}>
        {asset.totalSupply.eventCount > 0 ? supplied.display : "—"}
      </td>
      <td className="px-4 py-3 text-right font-mono text-foreground/90" title={`${borrowed.exact} ${asset.symbol} (exact)`}>
        {asset.totalBorrow.eventCount > 0 ? borrowed.display : "—"}
      </td>
      <td className="px-4 py-3 text-right font-mono text-foreground/90" title={`${repaid.exact} ${asset.symbol} (exact)`}>
        {asset.totalRepay.eventCount > 0 ? repaid.display : "—"}
      </td>
      <td
        className={`px-4 py-3 text-right font-mono font-medium ${
          netNumeric < 0 ? "text-negative" : netNumeric > 0 ? "text-positive" : "text-foreground/90"
        }`}
        title={`${net.exact} ${asset.symbol} (exact)`}
      >
        {netNumeric > 0 ? "+" : ""}
        {net.display}
      </td>
    </tr>
  );
}
